COMMON_INCLUDE_KEYWORDS = [
    "job",
    "jobs",
    "career",
    "careers",
    "intern",
    "internship",
    "graduate",
    "new-grad",
    "newgrad",
    "fresher",
    "students",
    "campus",
    "hiring",
    "opening",
    "opportunities",
    "hackathon",
    "challenge",
    "competition",
]

COMMON_EXCLUDE_KEYWORDS = [
    "blog",
    "press",
    "news",
    "privacy",
    "terms",
    "faq",
    "about",
    "contact",
    "support",
    "account",
    "applicant",
    "dashboard",
    "login",
    "logout",
    "passport",
    "profile",
    "signin",
    "signup",
    "user",
    "register",
]


COMPANIES = [
    {
        "name": "Devpost",
        "source_kind": "devpost_api",
        "pages": 8,
        "max_discovered_urls": 80,
    },
    {
        "name": "MLH",
        "source_kind": "seed_urls",
        "seed_urls": [
            "https://mlh.io/seasons/2026/events",
            "https://mlh.io/seasons/2025/events",
        ],
        "allowed_domains": ["mlh.io"],
        "include_keywords": ["event", "hack", "hackathon", "challenge"],
        "exclude_keywords": COMMON_EXCLUDE_KEYWORDS + ["sponsor", "organizer"],
        "per_seed_limit": 40,
        "max_discovered_urls": 50,
    },
    {
        "name": "Unstop",
        "source_kind": "seed_urls",
        "seed_urls": [
            "https://unstop.com/internships",
            "https://unstop.com/jobs",
            "https://unstop.com/hackathons",
        ],
        "allowed_domains": ["unstop.com"],
        "include_keywords": COMMON_INCLUDE_KEYWORDS,
        "exclude_keywords": COMMON_EXCLUDE_KEYWORDS,
        "per_seed_limit": 40,
        "max_discovered_urls": 90,
    },
    {
        "name": "Internshala",
        "source_kind": "seed_urls",
        "seed_urls": [
            "https://internshala.com/internships",
            "https://internshala.com/jobs",
        ],
        "allowed_domains": ["internshala.com"],
        "include_keywords": ["intern", "internship", "job", "jobs", "fresher", "student"],
        "exclude_keywords": COMMON_EXCLUDE_KEYWORDS,
        "per_seed_limit": 40,
        "max_discovered_urls": 80,
    },
    {
        "name": "Wellfound",
        "source_kind": "seed_urls",
        "seed_urls": [
            "https://wellfound.com/jobs",
        ],
        "allowed_domains": ["wellfound.com"],
        "include_keywords": ["job", "jobs", "intern", "internship"],
        "exclude_keywords": COMMON_EXCLUDE_KEYWORDS,
        "per_seed_limit": 40,
        "max_discovered_urls": 60,
    },
    {
        "name": "YC Jobs",
        "source_kind": "seed_urls",
        "seed_urls": [
            "https://www.ycombinator.com/jobs",
        ],
        "allowed_domains": ["ycombinator.com"],
        "include_keywords": ["jobs", "job", "intern", "internship"],
        "exclude_keywords": COMMON_EXCLUDE_KEYWORDS,
        "per_seed_limit": 40,
        "max_discovered_urls": 60,
    },
    {
        "name": "NewGrad.ai",
        "source_kind": "seed_urls",
        "seed_urls": [
            "https://newgrad.ai/",
        ],
        "allowed_domains": ["newgrad.ai"],
        "include_keywords": ["job", "jobs", "intern", "internship", "new-grad", "newgrad"],
        "exclude_keywords": COMMON_EXCLUDE_KEYWORDS,
        "per_seed_limit": 30,
        "max_discovered_urls": 40,
    },
    {
        "name": "Apna",
        "source_kind": "seed_urls",
        "seed_urls": [
            "https://apna.co/jobs",
        ],
        "allowed_domains": ["apna.co"],
        "include_keywords": ["job", "jobs", "intern", "internship", "fresher", "graduate"],
        "exclude_keywords": COMMON_EXCLUDE_KEYWORDS,
        "per_seed_limit": 30,
        "max_discovered_urls": 50,
    },
    {
        "name": "HackerEarth",
        "source_kind": "seed_urls",
        "seed_urls": [
            "https://www.hackerearth.com/challenges/",
            "https://www.hackerearth.com/recruit/",
        ],
        "allowed_domains": ["hackerearth.com"],
        "include_keywords": ["challenge", "hackathon", "hiring", "job", "intern", "competition"],
        "exclude_keywords": COMMON_EXCLUDE_KEYWORDS,
        "per_seed_limit": 40,
        "max_discovered_urls": 70,
    },
    {
        "name": "Kaggle Competitions",
        "source_kind": "seed_urls",
        "seed_urls": [
            "https://www.kaggle.com/competitions",
        ],
        "allowed_domains": ["kaggle.com"],
        "include_keywords": ["competition", "challenge"],
        "exclude_keywords": COMMON_EXCLUDE_KEYWORDS,
        "per_seed_limit": 30,
        "max_discovered_urls": 40,
    },
    {
        "name": "Google Careers",
        "source_kind": "sitemap",
        "base_url": "https://careers.google.com",
        "allowed_domains": ["careers.google.com"],
        "include_keywords": COMMON_INCLUDE_KEYWORDS + ["software", "data", "engineering", "student-training"],
        "exclude_keywords": COMMON_EXCLUDE_KEYWORDS,
        "max_discovered_urls": 80,
    },
    {
        "name": "Amazon Careers",
        "source_kind": "seed_urls",
        "seed_urls": [
            "https://www.amazon.jobs/en/search?base_query=intern",
            "https://www.amazon.jobs/en/search?base_query=software",
            "https://www.amazon.jobs/en/search?base_query=data",
        ],
        "allowed_domains": ["amazon.jobs"],
        "include_keywords": COMMON_INCLUDE_KEYWORDS + ["software", "data", "student-programs"],
        "exclude_keywords": COMMON_EXCLUDE_KEYWORDS,
        "per_seed_limit": 50,
        "max_discovered_urls": 120,
    },
    {
        "name": "Microsoft Careers",
        "source_kind": "seed_urls",
        "seed_urls": [
            "https://jobs.careers.microsoft.com/global/en/search?et=Internship",
            "https://jobs.careers.microsoft.com/global/en/search?et=Full-Time",
        ],
        "allowed_domains": ["jobs.careers.microsoft.com"],
        "include_keywords": COMMON_INCLUDE_KEYWORDS + ["software-engineering", "data", "cloud", "internship"],
        "exclude_keywords": COMMON_EXCLUDE_KEYWORDS,
        "per_seed_limit": 50,
        "max_discovered_urls": 100,
    },
    {
        "name": "Zoho Careers",
        "source_kind": "seed_urls",
        "seed_urls": [
            "https://www.zoho.com/careers/",
            "https://www.zoho.com/careers/job-openings.html",
        ],
        "allowed_domains": ["zoho.com"],
        "include_keywords": COMMON_INCLUDE_KEYWORDS + ["developer", "software", "engineer"],
        "exclude_keywords": COMMON_EXCLUDE_KEYWORDS,
        "per_seed_limit": 40,
        "max_discovered_urls": 80,
    },
    {
        "name": "Atlassian Careers",
        "source_kind": "seed_urls",
        "seed_urls": [
            "https://www.atlassian.com/company/careers/all-jobs",
        ],
        "allowed_domains": ["atlassian.com"],
        "include_keywords": COMMON_INCLUDE_KEYWORDS + ["student", "graduate", "software"],
        "exclude_keywords": COMMON_EXCLUDE_KEYWORDS,
        "per_seed_limit": 40,
        "max_discovered_urls": 60,
    },
    {
        "name": "Adobe Careers",
        "source_kind": "seed_urls",
        "seed_urls": [
            "https://careers.adobe.com/us/en/search-results",
        ],
        "allowed_domains": ["careers.adobe.com"],
        "include_keywords": COMMON_INCLUDE_KEYWORDS + ["software", "data", "student"],
        "exclude_keywords": COMMON_EXCLUDE_KEYWORDS,
        "per_seed_limit": 40,
        "max_discovered_urls": 60,
    },
    {
        "name": "Salesforce Careers",
        "source_kind": "seed_urls",
        "seed_urls": [
            "https://careers.salesforce.com/en/jobs/",
        ],
        "allowed_domains": ["careers.salesforce.com"],
        "include_keywords": COMMON_INCLUDE_KEYWORDS + ["software", "intern", "graduate"],
        "exclude_keywords": COMMON_EXCLUDE_KEYWORDS,
        "per_seed_limit": 40,
        "max_discovered_urls": 60,
    },
    {
        "name": "Nvidia Careers",
        "source_kind": "seed_urls",
        "seed_urls": [
            "https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite",
        ],
        "allowed_domains": ["nvidia.wd5.myworkdayjobs.com"],
        "include_keywords": COMMON_INCLUDE_KEYWORDS + ["software", "ai", "student"],
        "exclude_keywords": COMMON_EXCLUDE_KEYWORDS,
        "per_seed_limit": 40,
        "max_discovered_urls": 60,
    },
    {
        "name": "Oracle Careers",
        "source_kind": "seed_urls",
        "seed_urls": [
            "https://careers.oracle.com/jobs/",
        ],
        "allowed_domains": ["careers.oracle.com"],
        "include_keywords": COMMON_INCLUDE_KEYWORDS + ["software", "cloud", "intern"],
        "exclude_keywords": COMMON_EXCLUDE_KEYWORDS,
        "per_seed_limit": 40,
        "max_discovered_urls": 60,
    },
    {
        "name": "IBM Careers",
        "source_kind": "seed_urls",
        "seed_urls": [
            "https://www.ibm.com/careers/search",
        ],
        "allowed_domains": ["ibm.com"],
        "include_keywords": COMMON_INCLUDE_KEYWORDS + ["software", "intern", "graduate", "entry-level"],
        "exclude_keywords": COMMON_EXCLUDE_KEYWORDS,
        "per_seed_limit": 40,
        "max_discovered_urls": 60,
    },
    {
        "name": "Intel Careers",
        "source_kind": "seed_urls",
        "seed_urls": [
            "https://jobs.intel.com/en/search-jobs",
        ],
        "allowed_domains": ["jobs.intel.com"],
        "include_keywords": COMMON_INCLUDE_KEYWORDS + ["software", "intern", "graduate", "engineer"],
        "exclude_keywords": COMMON_EXCLUDE_KEYWORDS,
        "per_seed_limit": 40,
        "max_discovered_urls": 60,
    },
    {
        "name": "Uber Careers",
        "source_kind": "seed_urls",
        "seed_urls": [
            "https://www.uber.com/us/en/careers/list/",
        ],
        "allowed_domains": ["uber.com"],
        "include_keywords": COMMON_INCLUDE_KEYWORDS + ["software", "intern", "graduate", "engineering"],
        "exclude_keywords": COMMON_EXCLUDE_KEYWORDS,
        "per_seed_limit": 40,
        "max_discovered_urls": 60,
    },
    {
        "name": "Cisco Careers",
        "source_kind": "seed_urls",
        "seed_urls": [
            "https://jobs.cisco.com/jobs/SearchJobs/",
        ],
        "allowed_domains": ["jobs.cisco.com"],
        "include_keywords": COMMON_INCLUDE_KEYWORDS + ["software", "intern", "graduate", "engineering"],
        "exclude_keywords": COMMON_EXCLUDE_KEYWORDS,
        "per_seed_limit": 40,
        "max_discovered_urls": 60,
    },
    {
        "name": "ServiceNow Careers",
        "source_kind": "seed_urls",
        "seed_urls": [
            "https://careers.servicenow.com/careers/jobs",
        ],
        "allowed_domains": ["careers.servicenow.com"],
        "include_keywords": COMMON_INCLUDE_KEYWORDS + ["software", "intern", "graduate", "engineering"],
        "exclude_keywords": COMMON_EXCLUDE_KEYWORDS,
        "per_seed_limit": 40,
        "max_discovered_urls": 60,
    },
    {
        "name": "SAP Careers",
        "source_kind": "seed_urls",
        "seed_urls": [
            "https://jobs.sap.com/",
        ],
        "allowed_domains": ["jobs.sap.com"],
        "include_keywords": COMMON_INCLUDE_KEYWORDS + ["software", "intern", "graduate", "engineering"],
        "exclude_keywords": COMMON_EXCLUDE_KEYWORDS,
        "per_seed_limit": 40,
        "max_discovered_urls": 60,
    },
    {
        "name": "Greenhouse Boards",
        "source_kind": "seed_urls",
        "seed_urls": [
            "https://boards.greenhouse.io/stripe",
            "https://boards.greenhouse.io/datadog",
            "https://boards.greenhouse.io/coinbase",
            "https://boards.greenhouse.io/airtable",
            "https://boards.greenhouse.io/figma",
        ],
        "allowed_domains": ["boards.greenhouse.io"],
        "include_keywords": COMMON_INCLUDE_KEYWORDS + ["software", "intern", "university", "new-grad"],
        "exclude_keywords": COMMON_EXCLUDE_KEYWORDS,
        "per_seed_limit": 40,
        "max_discovered_urls": 120,
    },
    {
        "name": "Lever Boards",
        "source_kind": "seed_urls",
        "seed_urls": [
            "https://jobs.lever.co/postman",
            "https://jobs.lever.co/sourcegraph",
            "https://jobs.lever.co/canva",
            "https://jobs.lever.co/rippling",
        ],
        "allowed_domains": ["jobs.lever.co"],
        "include_keywords": COMMON_INCLUDE_KEYWORDS + ["software", "intern", "graduate", "university"],
        "exclude_keywords": COMMON_EXCLUDE_KEYWORDS,
        "per_seed_limit": 40,
        "max_discovered_urls": 100,
    },
    {
        "name": "Ashby Boards",
        "source_kind": "seed_urls",
        "seed_urls": [
            "https://jobs.ashbyhq.com/notion",
            "https://jobs.ashbyhq.com/ramp",
            "https://jobs.ashbyhq.com/perplexity",
            "https://jobs.ashbyhq.com/retool",
        ],
        "allowed_domains": ["jobs.ashbyhq.com"],
        "include_keywords": COMMON_INCLUDE_KEYWORDS + ["software", "intern", "graduate", "university"],
        "exclude_keywords": COMMON_EXCLUDE_KEYWORDS,
        "per_seed_limit": 40,
        "max_discovered_urls": 100,
    },
    {
        "name": "Naukri",
        "enabled": False,
        "source_kind": "seed_urls",
        "seed_urls": [
            "https://www.naukri.com/jobs-in-india",
        ],
        "allowed_domains": ["naukri.com"],
        "include_keywords": ["job", "jobs", "intern", "internship", "fresher"],
        "exclude_keywords": COMMON_EXCLUDE_KEYWORDS,
        "per_seed_limit": 40,
        "max_discovered_urls": 60,
    },
]
